import { randomUUID } from "node:crypto";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { XdrAuth, AuthenticationRequiredError } from "./auth.js";
import { loadConfig } from "./config.js";
import { runHuntingQuery } from "./client.js";
import { findSchemaTable, liveColumns, loadSchemaSnapshot, searchSchema } from "./schema.js";

const MAX_LINES = 2000, MAX_BYTES = 50 * 1024;
function bounded(value: unknown) { const text = JSON.stringify(value); if (Buffer.byteLength(text) <= MAX_BYTES && text.split("\n").length <= MAX_LINES) return text; return `${Buffer.from(text).subarray(0, MAX_BYTES).toString("utf8")}\n\n[Output truncated; refine the query or explicitly request export_results.]`; }
async function exportResult(result: unknown): Promise<string> { const directory = join(process.env.XDG_CONFIG_HOME || join(process.env.HOME || ".", ".config"), "claude-defender-xdr", "exports"); await mkdir(directory, { recursive: true, mode: 0o700 }); await chmod(directory, 0o700); const path = join(directory, `hunting-${new Date().toISOString().replace(/[:.]/g, "-")}-${randomUUID()}.json`); await writeFile(path, `${JSON.stringify(result, null, 2)}\n`, { encoding: "utf8", mode: 0o600, flag: "wx" }); await chmod(path, 0o600); return path; }
function errorResult(error: unknown) { const text = error instanceof AuthenticationRequiredError ? error.message : error instanceof Error ? error.message : String(error); return { content: [{ type: "text" as const, text: `Defender XDR error: ${text}` }], isError: true }; }
let configPromise: ReturnType<typeof loadConfig> | undefined, authPromise: Promise<XdrAuth> | undefined;
function config() { return configPromise ??= loadConfig(); }
function auth() { return authPromise ??= config().then(c => XdrAuth.create(c)); }
const server = new McpServer({ name: "defender-xdr", version: "0.1.0", description: "Read-only Microsoft Defender XDR Advanced Hunting via Microsoft Graph. Authentication is never started by tools; run claude-defender-xdr-login first." });
server.registerTool("xdr_run_query", { description: "Run a bounded, read-only KQL query against Microsoft Defender XDR Advanced Hunting. Never writes or changes tenant state. Use claude-defender-xdr-login when authentication is required.", inputSchema: { query: z.string().describe("Read-only KQL Advanced Hunting query"), timespan: z.string().optional().describe("7d, 24h, P7D, or PT24H"), max_rows: z.number().int().min(1).max(10000).optional(), export_results: z.boolean().optional().describe("Save complete results locally only when explicitly requested") } }, async ({ query, timespan, max_rows, export_results }) => { try { const [c, a] = await Promise.all([config(), auth()]); const r = await runHuntingQuery(a, c, { query, ...(timespan ? { timespan } : {}) }); const limit = Math.min(max_rows ?? c.maximumRows, c.maximumRows); const rows = r.results.slice(0, limit).map(row => Object.fromEntries(Object.entries(row).filter(([k]) => !k.endsWith("@odata.type")))); const payload = { totalRows: r.results.length, displayedRows: rows.length, rowsTruncated: rows.length < r.results.length, ...(rows.length === 0 ? { schema: r.schema } : {}), results: rows }; let text = bounded(payload); if (export_results) text += `\n\n[Complete owner-only result exported to ${await exportResult({ schema: r.schema, results: r.results })}]`; return { content: [{ type: "text" as const, text }] }; } catch (e) { return errorResult(e); } });
server.registerTool("xdr_get_schema", { description: "List, search, or describe Defender XDR Advanced Hunting tables and columns from the bundled official schema snapshot. Optionally verify an exact table against the tenant with take 0.", inputSchema: { table: z.string().optional(), search: z.string().optional(), live: z.boolean().optional(), include_retired: z.boolean().optional(), verbose: z.boolean().optional() } }, async ({ table, search, live, include_retired, verbose }) => { try { if (table && search) throw new Error("Specify either table or search, not both"); if (live && !table) throw new Error("live requires an exact table"); const s = await loadSchemaSnapshot(); if (table) { const t = await findSchemaTable(table); if (!t) throw new Error(`Unknown Defender XDR table ${JSON.stringify(table)}; possible matches: ${searchSchema(s, table, true, 5).map(x => x.table).join(", ")}`); if (t.status === "retired" && !include_retired) throw new Error(`${t.name} retired${t.replacedBy ? `; use ${t.replacedBy}` : ""}`); let payload: Record<string, unknown> = { name: t.name, description: t.description, status: t.status, ...(t.replacedBy ? { replacedBy: t.replacedBy, retirementDate: t.retirementDate } : {}), ...(verbose ? { documentationUrl: t.documentationUrl } : {}), columns: t.columns.map(c => verbose ? c : { name: c.name, type: c.type }) }; if (live) { const [c, a] = await Promise.all([config(), auth()]); const l = await liveColumns(t, a, c); payload = { ...payload, columns: l.columns, liveVerification: { fetchedAt: l.fetchedAt } }; } return { content: [{ type: "text" as const, text: bounded(payload) }] }; } const payload = search ? { search, matches: searchSchema(s, search, include_retired) } : { tables: s.tables.filter(t => include_retired || t.status !== "retired").map(({ name, description, status, replacedBy }) => ({ name, description, status, ...(replacedBy ? { replacedBy } : {}) })), sourceDate: s.sourceDate, sourceUrl: s.sourceUrl }; return { content: [{ type: "text" as const, text: bounded(payload) }] }; } catch (e) { return errorResult(e); } });
await server.connect(new StdioServerTransport());
